#!/usr/bin/env python3
"""
unified_index — local-first hybrid (FTS5 BM25 + neural vector, RRF-fused)
retrieval core.

ONE SQLite file holds, side-by-side, a unified chunk index over any number
of named sources (e.g. ``memory``, ``wiki``, ``obsidian``):

    chunks        — chunk text + metadata
    chunks_fts    — FTS5 BM25 keyword index
    chunks_vec    — sqlite-vec vec0 vector index

Embeddings: fastembed ``mixedbread-ai/mxbai-embed-large-v1`` (ONNX,
**zero torch**), dim 1024, output L2-normalised → vec0 default L2 distance
is monotonic with cosine similarity (no manual normalisation needed).

Retrieval is a single SQL statement: two rank lists (BM25 + vector KNN)
fused by Reciprocal Rank Fusion (k=60), plus a small bounded recency
tie-breaker. RRF needs only the rank from each arm, so BM25 scores and
vector distances never have to be normalised onto a common scale.

The module is intentionally side-effect-free on import (no model load, no
DB write) so multiple callers can import it cheaply and share one
retrieval code path.

Standalone check:  python mnemosyne/unified_index.py selftest
"""
from __future__ import annotations

import hashlib
import os
import re
import sqlite3
import struct
import subprocess
import sys
import threading
import time
from pathlib import Path
from typing import Iterable, Optional, Sequence

# Pinned to versions verified working (incl. on Intel x86_64 macOS, where
# torch>=2.6 has no wheels — fastembed is ONNX/onnxruntime, zero torch,
# which is the whole point of this stack).
_PINNED_DEPS = ("fastembed==0.8.0", "sqlite-vec==0.1.9")
DB_PATH = Path(
    os.environ.get("MNEMOSYNE_DB", "~/.mnemosyne/index.db")
).expanduser()
_HEAL_FLAG = DB_PATH.parent / ".mnemosyne_heal_attempt"
# Failure breadcrumb: when deps can't load, the exact reason is written
# here. A health watchdog (see docs) reads this so its alert says WHY,
# instead of a generic "memory down". Written only on failure / recovery
# transitions — never on the happy path (no per-call IO).
_HEALTH = _HEAL_FLAG.with_name(".mnemosyne_health")


def _write_health(status: str, detail: str = "") -> None:
    import json as _json
    try:
        _HEALTH.parent.mkdir(parents=True, exist_ok=True)
        _HEALTH.write_text(_json.dumps(
            {"status": status, "ts": time.time(), "detail": str(detail)[:600]}
        ))
    except OSError:
        pass


def _ensure_deps() -> None:
    """Self-heal: if the runtime's pip deps were wiped (e.g. a host venv
    was regenerated by an upgrade), reinstall them ONCE into *this*
    interpreter's environment, then continue. Idempotent, lazy, never
    loops (one attempt per interpreter process; a daily flag throttles
    cross-process retries).

    This is the structural guarantee that a venv-regenerating upgrade
    degrades to 'slower first call after upgrade', not 'semantic memory
    silently gone until someone notices'.
    """
    try:
        import fastembed  # noqa: F401
        import sqlite_vec  # noqa: F401
        return
    except Exception as _e:
        _import_error = _e  # captured so the failure breadcrumb says WHY
    if getattr(_ensure_deps, "_tried", False):
        _write_health("down", f"deps missing; self-heal already tried this "
                              f"process: {_import_error!r}")
        raise ImportError("mnemosyne deps missing and self-heal already "
                           "attempted this process")
    _ensure_deps._tried = True
    # Cross-process throttle: don't hammer pip on every call if heal keeps
    # failing — but keep the window SHORT. A long window turns a single
    # transient import failure (e.g. a host-restart race) into a long
    # outage; 30 min lets a transient self-recover fast instead. The happy
    # path (deps importable) returned above and never reaches here.
    _THROTTLE_SECONDS = 1800
    try:
        if _HEAL_FLAG.exists():
            age = time.time() - _HEAL_FLAG.stat().st_mtime
            if age >= _THROTTLE_SECONDS:
                _HEAL_FLAG.unlink()  # STALE → remove proactively, never linger
            else:
                _write_health("down", f"deps missing; heal throttled, "
                              f"{int(_THROTTLE_SECONDS - age)}s left: {_import_error!r}")
                raise ImportError("mnemosyne deps missing; recent heal attempt "
                                  "failed (throttled 30min, self-recovers)")
    except OSError:
        pass
    try:
        _HEAL_FLAG.parent.mkdir(parents=True, exist_ok=True)
        _HEAL_FLAG.touch()
    except OSError:
        pass
    sys.stderr.write("[mnemosyne] deps missing — self-healing: pip install "
                     f"{' '.join(_PINNED_DEPS)}\n")
    sys.stderr.flush()
    # Prefer uv (fast) if present; fall back to pip -m.
    for cmd in (["uv", "pip", "install", *_PINNED_DEPS],
                [sys.executable, "-m", "pip", "install", *_PINNED_DEPS]):
        try:
            env = dict(os.environ)
            env.setdefault("VIRTUAL_ENV", str(Path(sys.executable).parent.parent))
            r = subprocess.run(cmd, capture_output=True, text=True,
                               timeout=600, env=env)
            if r.returncode == 0:
                break
        except (FileNotFoundError, subprocess.SubprocessError):
            continue
    import importlib
    importlib.invalidate_caches()
    try:
        import fastembed  # noqa: F401
        import sqlite_vec  # noqa: F401
    except Exception as _he:
        _write_health("down", f"self-heal pip install did not fix it: {_he!r}")
        raise
    _write_health("ok", "recovered via self-heal")
    try:
        _HEAL_FLAG.unlink()  # success → clear the throttle
    except OSError:
        pass

# ── Constants ────────────────────────────────────────────────────────────────
MODEL_ID = "mixedbread-ai/mxbai-embed-large-v1"
EMBED_DIM = 1024
SCHEMA_VERSION = 1
RRF_K = 60  # sqlite-vec author's published hybrid-fusion constant

# Recency tie-breaker: a fresher chunk should edge out a stale one on a
# near-tie. Bounded so it only flips near-ties — max contribution ≈ 30% of
# one RRF rank step, never enough to surface an irrelevant-but-fresh doc.
# Half-life in days; mtime=None (e.g. a memory fact) = neutral.
_RECENCY_HALFLIFE_DAYS = 30.0
_RECENCY_W = 0.3  # × (1/RRF_K) is the peak additive boost

# token≈chars/4 heuristic; mxbai context is 512 tok → ~2048 chars target,
# ~256-char (~64 tok) overlap between adjacent chunks of an oversized section.
_CHUNK_TARGET_CHARS = 2048
_CHUNK_OVERLAP_CHARS = 256

# Optional per-chunk down-weight (caller may tag chunks via lint_flag, e.g.
# from a staleness/structure linter). Index-with-down-weight, never exclude.
_LINT_WEIGHT = {None: 1.0, "": 1.0, "orphan": 0.9, "stale": 0.7, "contradiction": 0.6}

# ── Embedder (lazy, thread-safe singleton) ───────────────────────────────────
_embedder = None
_embedder_lock = threading.Lock()


def get_embedder():
    """fastembed singleton. First call downloads the ONNX model (~0.64 GB)."""
    global _embedder
    if _embedder is None:
        with _embedder_lock:
            if _embedder is None:
                _ensure_deps()
                from fastembed import TextEmbedding

                _embedder = TextEmbedding(model_name=MODEL_ID)
    return _embedder


def embed_texts(texts: Sequence[str]) -> list[bytes]:
    """Embed a batch → list of vec0-serialisable little-endian float32 blobs."""
    if not texts:
        return []
    vecs = get_embedder().embed(list(texts))
    return [_serialize_f32(v) for v in vecs]


def _serialize_f32(vec) -> bytes:
    v = list(vec)
    return struct.pack(f"{len(v)}f", *v)


# ── Connection ───────────────────────────────────────────────────────────────
def connect(db_path: Optional[os.PathLike | str] = None) -> sqlite3.Connection:
    """Open the DB with WAL + the sqlite-vec extension loaded.

    WAL allows concurrent readers while a writer upserts (multi-reader,
    single-writer). The extension only loads on a Python whose ``sqlite3``
    was built with ``enable_load_extension`` (true for most CPython
    distributions; NOT Apple's system python — use a standalone/venv python).
    """
    _ensure_deps()
    import sqlite_vec

    target = str(db_path or DB_PATH)
    if target != ":memory:":
        Path(target).expanduser().parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(target)
    conn.execute("PRAGMA journal_mode = WAL")
    conn.execute("PRAGMA busy_timeout = 5000")
    conn.enable_load_extension(True)
    sqlite_vec.load(conn)
    conn.enable_load_extension(False)
    return conn


# ── Schema ───────────────────────────────────────────────────────────────────
def init_schema(conn: sqlite3.Connection) -> None:
    conn.executescript(
        f"""
        CREATE TABLE IF NOT EXISTS chunks (
            chunk_id    INTEGER PRIMARY KEY AUTOINCREMENT,
            doc_id      TEXT NOT NULL,        -- stable per-source doc key
            source      TEXT NOT NULL,        -- caller-defined source label
            path        TEXT,                 -- absolute fs path (optional)
            rel_path    TEXT,                 -- root-relative (optional)
            title       TEXT,
            ord         INTEGER NOT NULL,     -- chunk order within doc
            content     TEXT NOT NULL,
            doc_sha     TEXT NOT NULL,        -- sha256 of whole doc (change guard)
            mtime       REAL,
            lint_flag   TEXT,                 -- NULL|orphan|stale|contradiction
            indexed_at  REAL NOT NULL
        );
        CREATE INDEX IF NOT EXISTS idx_chunks_doc    ON chunks(doc_id);
        CREATE INDEX IF NOT EXISTS idx_chunks_source ON chunks(source);

        CREATE VIRTUAL TABLE IF NOT EXISTS chunks_fts USING fts5(
            content,
            chunk_id UNINDEXED,
            tokenize = 'porter unicode61'
        );

        CREATE VIRTUAL TABLE IF NOT EXISTS chunks_vec USING vec0(
            embedding float[{EMBED_DIM}]
        );

        CREATE TABLE IF NOT EXISTS index_meta (
            key TEXT PRIMARY KEY,
            value TEXT
        );
        """
    )
    meta = dict(conn.execute("SELECT key, value FROM index_meta").fetchall())
    if not meta:
        conn.executemany(
            "INSERT OR REPLACE INTO index_meta(key,value) VALUES(?,?)",
            [
                ("schema_version", str(SCHEMA_VERSION)),
                ("model_id", MODEL_ID),
                ("embed_dim", str(EMBED_DIM)),
            ],
        )
    elif meta.get("model_id") != MODEL_ID or meta.get("embed_dim") != str(EMBED_DIM):
        raise RuntimeError(
            f"unified_index: model/dim mismatch — DB built with "
            f"{meta.get('model_id')}/{meta.get('embed_dim')}, code expects "
            f"{MODEL_ID}/{EMBED_DIM}. Re-embed required before reuse."
        )
    conn.commit()


# ── Chunking ─────────────────────────────────────────────────────────────────
_HEADING_RE = re.compile(r"^(#{1,6})\s+\S", re.MULTILINE)


def _sha(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8", "replace")).hexdigest()


def _window(text: str) -> list[str]:
    """Sliding-window split for a single oversized section."""
    out, i, n = [], 0, len(text)
    step = _CHUNK_TARGET_CHARS - _CHUNK_OVERLAP_CHARS
    while i < n:
        out.append(text[i : i + _CHUNK_TARGET_CHARS])
        i += step
    return out


def chunk_text(text: str, kind: str = "markdown") -> list[str]:
    """Heading-aware markdown chunking; a short fact is a single chunk.

    Generic ``## section`` blocks (e.g. dated journal entries) are kept
    intact by the heading splitter, so no special-casing is needed.
    """
    text = text.strip()
    if not text:
        return []
    if kind == "fact":
        return [text] if len(text) <= _CHUNK_TARGET_CHARS else _window(text)

    # Split at heading boundaries, keep heading with its body.
    bounds = [m.start() for m in _HEADING_RE.finditer(text)]
    if not bounds or bounds[0] != 0:
        bounds = [0] + bounds
    sections = [
        text[bounds[i] : (bounds[i + 1] if i + 1 < len(bounds) else len(text))].strip()
        for i in range(len(bounds))
    ]
    sections = [s for s in sections if s]

    chunks: list[str] = []
    buf = ""
    for sec in sections:
        if len(sec) > _CHUNK_TARGET_CHARS:
            if buf:
                chunks.append(buf)
                buf = ""
            chunks.extend(_window(sec))
        elif len(buf) + len(sec) + 2 <= _CHUNK_TARGET_CHARS:
            buf = f"{buf}\n\n{sec}" if buf else sec
        else:
            if buf:
                chunks.append(buf)
            buf = sec
    if buf:
        chunks.append(buf)
    return chunks or [text[:_CHUNK_TARGET_CHARS]]


# ── Upsert / delete (vec0 has no UPSERT → delete-by-doc then re-insert) ───────
def _chunk_ids_for_doc(conn: sqlite3.Connection, doc_id: str) -> list[int]:
    return [r[0] for r in conn.execute(
        "SELECT chunk_id FROM chunks WHERE doc_id = ?", (doc_id,)
    )]


def delete_doc(conn: sqlite3.Connection, doc_id: str) -> int:
    """Purge all chunks for a doc from all three tables. Returns #removed."""
    ids = _chunk_ids_for_doc(conn, doc_id)
    if not ids:
        return 0
    conn.execute("BEGIN IMMEDIATE")
    try:
        qm = ",".join("?" * len(ids))
        conn.execute(f"DELETE FROM chunks_vec WHERE rowid IN ({qm})", ids)
        conn.execute(f"DELETE FROM chunks_fts WHERE chunk_id IN ({qm})", ids)
        conn.execute(f"DELETE FROM chunks WHERE chunk_id IN ({qm})", ids)
        conn.execute("COMMIT")
    except Exception:
        conn.execute("ROLLBACK")
        raise
    return len(ids)


def upsert_doc(
    conn: sqlite3.Connection,
    *,
    doc_id: str,
    source: str,
    text: str,
    path: Optional[str] = None,
    rel_path: Optional[str] = None,
    title: Optional[str] = None,
    mtime: Optional[float] = None,
    lint_flag: Optional[str] = None,
    kind: str = "markdown",
) -> str:
    """Idempotent re-index of one doc. Returns 'skipped' | 'indexed' | 'empty'.

    Content-SHA guard: unchanged body + unchanged lint_flag → no re-embed
    (the expensive step). Everything is one IMMEDIATE txn so a crashed
    writer never leaves the three tables out of sync.
    """
    doc_sha = _sha(text)
    existing = conn.execute(
        "SELECT doc_sha, lint_flag FROM chunks WHERE doc_id = ? LIMIT 1", (doc_id,)
    ).fetchone()
    if existing and existing[0] == doc_sha and (existing[1] or None) == (lint_flag or None):
        return "skipped"

    pieces = chunk_text(text, kind=kind)
    if not pieces:
        delete_doc(conn, doc_id)
        return "empty"

    blobs = embed_texts(pieces)  # outside the txn — the slow part
    old_ids = _chunk_ids_for_doc(conn, doc_id)
    now = time.time()

    conn.execute("BEGIN IMMEDIATE")
    try:
        if old_ids:
            qm = ",".join("?" * len(old_ids))
            conn.execute(f"DELETE FROM chunks_vec WHERE rowid IN ({qm})", old_ids)
            conn.execute(f"DELETE FROM chunks_fts WHERE chunk_id IN ({qm})", old_ids)
            conn.execute(f"DELETE FROM chunks WHERE chunk_id IN ({qm})", old_ids)
        for ordn, (piece, blob) in enumerate(zip(pieces, blobs)):
            cur = conn.execute(
                """INSERT INTO chunks
                   (doc_id, source, path, rel_path, title, ord, content,
                    doc_sha, mtime, lint_flag, indexed_at)
                   VALUES (?,?,?,?,?,?,?,?,?,?,?)""",
                (doc_id, source, path, rel_path, title, ordn, piece,
                 doc_sha, mtime, lint_flag, now),
            )
            cid = cur.lastrowid
            conn.execute(
                "INSERT INTO chunks_fts(content, chunk_id) VALUES (?,?)", (piece, cid)
            )
            conn.execute(
                "INSERT INTO chunks_vec(rowid, embedding) VALUES (?,?)", (cid, blob)
            )
        conn.execute("COMMIT")
    except Exception:
        conn.execute("ROLLBACK")
        raise
    return "indexed"


# ── Hybrid retrieval — single SELECT, 3 CTEs, RRF k=60 ───────────────────────
def hybrid_search(
    conn: sqlite3.Connection,
    query: str,
    *,
    sources: Optional[Iterable[str]] = None,
    k: int = 10,
    pool: int = 50,
    w_fts: float = 1.0,
    w_vec: float = 1.0,
    lint_downweight: bool = True,
) -> list[dict]:
    """Keyword (BM25) ⊕ neural-vector results fused by Reciprocal Rank Fusion.

        score = w_fts/(K + fts_rank) + w_vec/(K + vec_rank)        (K = 60)

    Each arm independently retrieves `pool` candidates; RRF needs only the
    rank, not the raw score, so BM25 and L2 distance never have to be
    normalised onto a common scale — that scale-invariance is the whole
    point of RRF and why it beats score-weighted fusion here.

    `sources=None` searches every source; pass a subset to scope it.
    """
    query = (query or "").strip()
    if not query:
        return []
    if sources is None:
        rows = conn.execute("SELECT DISTINCT source FROM chunks").fetchall()
        src = tuple(r[0] for r in rows) or ("__none__",)
    else:
        src = tuple(sources)
    src_ph = ",".join(f":s{i}" for i in range(len(src)))
    qvec = embed_texts([query])[0]

    sql = f"""
    WITH
    v AS (
        SELECT rowid AS chunk_id,
               ROW_NUMBER() OVER (ORDER BY distance) AS rnk
        FROM chunks_vec
        WHERE embedding MATCH :qvec AND k = :pool
    ),
    f AS (
        SELECT chunk_id,
               ROW_NUMBER() OVER (ORDER BY bm25(chunks_fts)) AS rnk
        FROM chunks_fts
        WHERE chunks_fts MATCH :q
        LIMIT :pool
    ),
    fused AS (
        SELECT COALESCE(v.chunk_id, f.chunk_id) AS chunk_id,
               (CASE WHEN f.rnk IS NULL THEN 0 ELSE :wf / (:rk + f.rnk) END) +
               (CASE WHEN v.rnk IS NULL THEN 0 ELSE :wv / (:rk + v.rnk) END)
                   AS rrf
        FROM v
        FULL OUTER JOIN f ON v.chunk_id = f.chunk_id
    )
    SELECT c.chunk_id, c.doc_id, c.source, c.path, c.rel_path, c.title,
           c.ord, c.content, c.lint_flag, fused.rrf, c.mtime
    FROM fused
    JOIN chunks c ON c.chunk_id = fused.chunk_id
    WHERE c.source IN ({src_ph})
    ORDER BY fused.rrf DESC
    LIMIT :poollim
    """
    params = {
        "qvec": qvec, "q": query, "pool": pool,
        "wf": w_fts, "wv": w_vec, "rk": RRF_K,
        "poollim": max(k * 4, pool),
    }
    for i, s in enumerate(src):
        params[f"s{i}"] = s
    cur = conn.execute(sql, params)
    now = time.time()
    peak_recency = _RECENCY_W / RRF_K
    results = []
    for r in cur.fetchall():
        flag = r[8]
        weight = _LINT_WEIGHT.get(flag, 0.8) if lint_downweight else 1.0
        mtime = r[10]
        if mtime:
            age_days = max(0.0, (now - mtime) / 86400.0)
            recency = peak_recency * (0.5 ** (age_days / _RECENCY_HALFLIFE_DAYS))
        else:
            recency = 0.0
        results.append(
            {
                "chunk_id": r[0], "doc_id": r[1], "source": r[2],
                "path": r[3], "rel_path": r[4], "title": r[5],
                "ord": r[6], "content": r[7], "lint_flag": flag,
                "score": r[9] * weight + recency,
            }
        )
    results.sort(key=lambda x: x["score"], reverse=True)
    return results[:k]


# ── Stats ────────────────────────────────────────────────────────────────────
def corpus_stats(conn: sqlite3.Connection) -> dict:
    out = {"chunks": 0, "by_source": {}, "docs": 0}
    try:
        out["chunks"] = conn.execute("SELECT COUNT(*) FROM chunks").fetchone()[0]
        out["docs"] = conn.execute(
            "SELECT COUNT(DISTINCT doc_id) FROM chunks"
        ).fetchone()[0]
        for s, n in conn.execute(
            "SELECT source, COUNT(*) FROM chunks GROUP BY source"
        ):
            out["by_source"][s] = n
    except sqlite3.OperationalError:
        pass
    return out


# ── Selftest ─────────────────────────────────────────────────────────────────
def _selftest() -> int:
    """End-to-end check with real fastembed + vec0, fully in-memory.

    Uses neutral synthetic fixtures. Verifies: paraphrased semantic recall
    (the vector arm earns its keep — queries share no exact keyword with
    the target), source-filter isolation, and content-SHA idempotency.
    """
    print("unified_index selftest — in-memory, real fastembed + vec0")
    conn = connect(":memory:")
    init_schema(conn)
    docs = [
        ("wiki", "wiki:guides/deploy.md",
         "# Deployment Guide\nThe service ships via a blue-green rollout. "
         "A health probe gates promotion; a failed probe rolls the release "
         "back automatically with no operator action."),
        ("obsidian", "obsidian:notes/sourdough.md",
         "# Sourdough Notes\nHydration around 75% yields an open crumb. "
         "Retarding the shaped dough in the fridge overnight develops a "
         "noticeably deeper, more sour flavour."),
        ("memory", "memory:fact:1",
         "The user prefers tabs over spaces and a dark editor theme."),
    ]
    for source, did, txt in docs:
        st = upsert_doc(conn, doc_id=did, source=source, text=txt,
                        title=did, kind="fact" if source == "memory" else "markdown")
        print(f"  upsert {did:28s} -> {st}")
    print("  stats:", corpus_stats(conn))

    ok = True
    # Each query is a paraphrase with ~no lexical overlap with its target —
    # so a hit proves the neural arm (not just BM25) is working.
    cases = [
        ("how does releasing avoid downtime", "wiki:guides/deploy.md"),
        ("why rest bread dough in the fridge", "obsidian:notes/sourdough.md"),
        ("editor indentation preference", "memory:fact:1"),
    ]
    for q, want in cases:
        res = hybrid_search(conn, q, k=3)
        top = res[0]["doc_id"] if res else None
        flag = "OK " if top == want else "FAIL"
        if top != want:
            ok = False
        print(f"  [{flag}] q={q!r:36s} top={top}")

    # idempotency: re-upsert unchanged → skipped (no re-embed)
    st = upsert_doc(conn, doc_id=docs[0][1], source="wiki", text=docs[0][2],
                    kind="markdown")
    print(f"  idempotent re-upsert -> {st} (expect 'skipped')")
    ok = ok and st == "skipped"

    # source filter isolates the corpus
    only_mem = hybrid_search(conn, "preference", sources=["memory"], k=5)
    iso = all(r["source"] == "memory" for r in only_mem)
    print(f"  source-filter isolation: {'OK' if iso else 'FAIL'}")
    ok = ok and iso

    print("RESULT:", "PASS" if ok else "FAIL")
    return 0 if ok else 1


if __name__ == "__main__":
    if len(sys.argv) > 1 and sys.argv[1] == "selftest":
        raise SystemExit(_selftest())
    print(__doc__)
